const T = {
"brand.sub":{ja:"ポートフォリオ",en:"Portfolio"},
"ui.scroll":{ja:"スクロール",en:"Scroll"},
"ui.fit":{ja:"全体",en:"Fit"},
"ui.lbhelp":{ja:"ドラッグで移動 ・ ホイールで拡大縮小 ・ Esc で閉じる",en:"Drag to pan · Scroll to zoom · Esc to close"},
"ui.zoom":{ja:"クリックで拡大",en:"Click to enlarge"},
"ui.loading":{ja:"読み込み中…",en:"Loading…"},
"ui.openyt":{ja:"YouTubeで開く",en:"Open on YouTube"},

"nav.flagship":{ja:"主要プロジェクト",en:"Flagships"},
"nav.labo":{ja:"BP Labo",en:"BP Labo"},
"nav.td":{ja:"TalentDesk",en:"TalentDesk"},
"nav.web":{ja:"Webサイト",en:"Website"},
"nav.ai":{ja:"AI・自動化",en:"AI & automation"},
"nav.video":{ja:"映像",en:"Video"},
"nav.design":{ja:"デザイン",en:"Design"},
"nav.fuji":{ja:"フジィ・スタジオ",en:"Fujie Studio"},
"nav.hr":{ja:"人事・運営",en:"HR & ops"},

/* ── HERO ── */
"h.eye":{ja:"ポートフォリオ ・ 2026",en:"Portfolio · 2026"},
"h.nick":{ja:"通称 <b>「Don（ドン）」</b>。周囲にはこの名前で呼ばれています。",en:"Everyone calls me <b>Don</b>."},
"h.role":{ja:"株式会社ブレーンパワーのソフトウェアを、設計から開発・運用まで一人で担当しています。<br>業務システム、Web・アプリ開発、AIエージェント構築。",
          en:"I design, build and run all of the software at Brain Power — business systems, web and app development, and AI agents."},
"h.m1t":{ja:"所属",en:"Company"},
"h.m1":{ja:"株式会社ブレーンパワー<br>大阪・ALT派遣事業",en:"Brain Power Inc.<br>ALT dispatch, Osaka"},
"h.m2t":{ja:"現在の役割",en:"Current role"},
"h.m2":{ja:"エージェンティック／システムエンジニア<br>Web・アプリ・業務システム開発",en:"Agentic / systems engineer<br>Web, app & business systems"},
"h.m3t":{ja:"つくったもの",en:"Built"},
"h.m3":{ja:"Webアプリ 30本以上<br>動画・教材 40本以上",en:"30+ web apps<br>40+ videos &amp; teaching assets"},
"h.m4t":{ja:"言語",en:"Languages"},
"h.m4":{ja:"英語（母語）／日本語<br>全システム日英対応",en:"English (native) / Japanese<br>Everything shipped bilingual"},

/* ── AT A GLANCE ── */
"i.eye":{ja:"概要",en:"At a glance"},
"i.h":{ja:"派遣会社の業務を、<br><em>ひとつずつソフトウェアに</em>置き換えてきました。",
       en:"I have replaced a dispatch company's paperwork,<br><em>one system at a time.</em>"},
"i.lead":{ja:"株式会社ブレーンパワーは、大阪府内の公立小中学校へ外国語指導助手（ALT）を派遣する会社です。私はここで、<strong>勤怠・給与関連書類・在留資格・採用・研修・授業支援</strong>のほぼ全てを、自分で設計したWebシステムに置き換えました。加えて、広告デザイン、キャラクター制作、動画制作、SNS運用、そして日々の人事・労務実務も担当しています。<strong>企画から開発、デザイン、運用までを一人で完結できること</strong>が私の強みです。",
          en:"Brain Power dispatches Assistant Language Teachers to public elementary and junior high schools across Osaka. Over my time here I have moved almost everything that used to run on paper and spreadsheets — <strong>attendance, payroll documents, visa status, hiring, training and classroom support</strong> — into web systems I designed and built myself. Alongside that I handle advertising design, character design, video production, social media and the day-to-day HR work. <strong>I can take something from idea to running system on my own</strong>, and that is what I am offering."},
"i.s1":{ja:"自社開発したWebアプリ・サイト",en:"Web apps & sites built"},
"i.s2":{ja:"システムで管理する社員数",en:"Staff managed in the system"},
"i.s3":{ja:"登録校数（10市町村）",en:"Schools on file, across 10 cities"},
"i.s4":{ja:"年間の勤務日データを自動集計",en:"Working days tracked per year"},
"i.s5":{ja:"全システムを日英両対応で設計",en:"Every system shipped in both"},
"i.c1h":{ja:"つくる人",en:"I build it"},
"i.c1p":{ja:"要件定義・画面設計・実装・デザイン・運用まで一人で担当。外注なし、社内で完結。",
         en:"Requirements, screen design, build, visual design and day-to-day operation — all in-house, all by me. Nothing outsourced."},
"i.c2h":{ja:"回す人",en:"I run it"},
"i.c2p":{ja:"作って終わりではなく、実際に毎日その業務を回している当事者として改善を続けています。",
         en:"I do not hand systems over and walk away. I am the person who runs the operation every day, so the systems keep getting fixed."},
"i.c3h":{ja:"伝える人",en:"I explain it"},
"i.c3p":{ja:"マニュアル、研修、動画、ガイドサイト。使われなければ意味がないので、教える所までやります。",
         en:"Manuals, training sessions, videos, guide sites. A system nobody understands is not finished, so I teach it too."},

/* ── FLAGSHIPS ── */
"f.eye":{ja:"主要プロジェクト",en:"The two that matter most"},
"f.h":{ja:"基幹となる<em>2つのシステム</em>",en:"Two systems<em> carry the business</em>"},
"f.lead":{ja:"どちらも私が一人で企画し、設計し、構築したものです。片方は自社の全社員と全校を動かす社内基盤。もう片方は、クライアント企業・自社・複数の協力会社をひとつの記録でつなぐ、派遣業務の管理システムです。",
          en:"I conceived, designed and built both on my own. One is the internal platform that runs every member of staff and every school we serve. The other connects a client company, us, and a group of partner agencies around a single shared record."},
"f.a1h":{ja:"BP Labo — 社内プラットフォーム",en:"BP Labo — the internal platform"},
"f.a1p":{ja:"社員が使う業務アプリと、教員が教室で使う授業アプリ。合わせて20本以上を、ひとつのログインの下にまとめたハブサイト。中核が自社開発のHRISです。",
         en:"Twenty-plus applications behind one login — the back-office systems staff use, and the classroom apps our teachers use in front of students. At its centre sits a custom-built HRIS."},
"f.a1c1":{ja:"自社開発HRIS",en:"Custom HRIS"},
"f.a1c2":{ja:"20以上のアプリ",en:"20+ apps"},
"f.a1c3":{ja:"63名が日常利用",en:"63 daily users"},
"f.a2h":{ja:"TalentDesk — MSPプラットフォーム",en:"TalentDesk — an MSP platform"},
"f.a2p":{ja:"Brain Power が<strong>MSP（マネージド・サービス・プロバイダ）</strong>として、クライアント企業フジキンの人材要求を受け、何社でも登録できる協力会社群に配信し、全体を一元管理するためのプラットフォーム。派遣法の抵触日も自動で監視します。",
         en:"The platform Brain Power runs as a <strong>managed service provider</strong> — taking Fujikin’s staffing requests, releasing them to however many supplier agencies are registered, and managing the whole programme from one place, with the dispatch-law clocks watched automatically."},
"f.a2c1":{ja:"MSPモデル",en:"MSP model"},
"f.a2c2":{ja:"派遣法コンプライアンス",en:"Dispatch-law compliance"},
"f.a2c3":{ja:"AI選考支援",en:"AI screening"},

/* ── BP LABO ── */
"l.eye":{ja:"01 — bplabo.jp",en:"01 — bplabo.jp"},
"l.h":{ja:"ひとつのログインの先に、<br><em>会社の仕事が全部ある。</em>",en:"One login.<br><em>The whole company behind it.</em>"},
"l.lead":{ja:"BP Laboは、私が構築した社内プラットフォームです。社員は入社初日にここのアカウントを受け取り、以降<strong>出退勤、勤務表、有給申請、月次報告、在留資格の更新、年末調整、研修、授業準備</strong>まで、すべてここから行います。管理側と教員側で見える範囲が分かれており、権限は個人単位で設定します。",
          en:"BP Labo is the internal platform I built. A new member of staff gets an account on day one and from then on everything runs through it — <strong>clocking in, timesheets, leave requests, monthly reports, visa renewals, year-end tax, training and lesson preparation</strong>. Administrators and teachers see different halves of it, and access is set person by person."},
"l.f1b":{ja:"ひとつのアカウント",en:"One account"},
"l.f1s":{ja:"入社時に発行。全アプリ共通、権限は個人ごとに設定。",en:"Issued on the first day. One sign-in for every app, with permissions set per person."},
"l.f2b":{ja:"管理側",en:"The office"},
"l.f2s":{ja:"人事・勤怠・在留資格・採用・分析を担当者が扱う画面。",en:"Where HR, attendance, visas, hiring and analytics are actually worked."},
"l.f3b":{ja:"教員側",en:"The teachers"},
"l.f3s":{ja:"授業で使うアプリ、社内規定、研修資料、生活情報。",en:"Classroom apps, company rules, training material and living-in-Japan guidance."},
"l.f4b":{ja:"日英両対応",en:"Both languages"},
"l.f4s":{ja:"外国籍社員が大半のため、全画面を日英で用意。",en:"Most of our staff are not Japanese, so every screen exists in both languages."},
"l.btn":{ja:"bplabo.jp を開いてログインする",en:"Open bplabo.jp and sign in"},
"l.demoh":{ja:"閲覧用アカウント",en:"Guest account"},
"l.demop":{ja:"こちらでログインして、実際のシステムを自由にご覧ください。",en:"Sign in with this and browse the real system freely."},
"l.demou":{ja:"ユーザー名",en:"Username"},
"l.demopw":{ja:"パスワード",en:"Password"},
"l.demonote":{ja:"<b>管理者用のHRIS（ALTダッシュボード）は、セキュリティ上このアカウントでは開けません。</b>社員の個人情報・給与・在留資格のデータを扱うためです。それ以外のアプリはすべて自由にお試しいただけます。管理画面の中身は、次のセクションのスクリーンショットでご覧ください。",
              en:"<b>The admin HRIS — the ALT Dashboard — is closed to this account, for security reasons.</b> It holds staff personal data, pay and visa records. Everything else on the platform is open to you. The section below shows the admin side screen by screen."},
"ui.copy":{ja:"コピー",en:"Copy"},
"ui.copied":{ja:"コピー済み",en:"Copied"},

/* ── DASHBOARD ── */
"d.eye":{ja:"BP Labo の中核",en:"The heart of BP Labo"},
"d.h":{ja:"自社開発の<em>HRIS</em>。<br>人事のすべてが、ここに集まる。",
       en:"A custom-built <em>HRIS</em>.<br>Every HR fact in one place."},
"d.lead":{ja:"市販の人事システムでは、ALT派遣という業務——<strong>誰がどの学校に何曜日に行くか、在留資格はいつ切れるか、何コマ授業を持ったか</strong>——を扱えませんでした。そこで自分で作りました。勤怠、スケジュール、契約、有給、在留資格、採用、研修、分析までを1つのシステムで扱い、担当者は毎朝この画面を開いて一日を始めます。",
          en:"No off-the-shelf HR product could handle what this business actually is — <strong>who is at which school on which day, whose visa expires when, how many periods each person taught</strong>. So I built one. Attendance, scheduling, contracts, paid leave, residence status, recruitment, training and analytics all live in a single system, and the office opens this page to start the day."},
"d.s1":{ja:"管理下の社員アカウント",en:"Staff accounts managed"},
"d.s2":{ja:"登録校数",en:"Schools on file"},
"d.s3":{ja:"担当市町村",en:"Cities served"},
"d.s4":{ja:"年間勤務日データ",en:"Working days per year"},
"d.s5":{ja:"連携する業務モジュール",en:"Connected modules"},
"d.caph":{ja:"できること",en:"What it does"},
"d.k1h":{ja:"スケジュール管理",en:"Scheduling"},
"d.k1p":{ja:"社員ごとの月間カレンダーに、日ごとの配属校を色分けで表示。振替授業も区別して表示し、予定・遅刻・欠勤・早退を自動集計します。",
         en:"A month calendar per person with the assigned school colour-coded on every working day, make-up days shown separately, and scheduled / late / absent / early-leave totals counted automatically."},
"d.k2h":{ja:"出退勤（On My Way）",en:"Live check-in"},
"d.k2p":{ja:"出勤済・未出勤・休みの3列でリアルタイム表示。未出勤者にはワンクリックで催促、欠勤理由と配属校・学校電話番号もその場で確認できます。",
         en:"A live board split into checked in, not checked in and off — with one-click reminders, the absence reason, and the assigned school's phone number right there."},
"d.k3h":{ja:"デジタル勤務表",en:"Digital timesheets"},
"d.k3p":{ja:"1日ごとに始業・終業・1〜6時限・休憩を記録し、勤務日数と時間を自動計算。未提出者の一覧と個別の催促送信も可能です。",
         en:"Start, finish, six teaching periods and break recorded per day, with days and hours totalled automatically — plus a list of who has not submitted and a reminder button for each."},
"d.k4h":{ja:"有給・休暇申請",en:"Leave requests"},
"d.k4p":{ja:"申請・承認・代替教員の割当・振替日の設定までを1画面で処理。緊急案件は上部に警告表示され、見落としを防ぎます。",
         en:"Request, approve, assign a substitute and set the make-up date on one screen. Urgent items are flagged at the top so they cannot be missed."},
"d.k5h":{ja:"在留資格の期限管理",en:"Visa expiry tracking"},
"d.k5p":{ja:"社員ごとの在留期限を残日数付きで一覧表示。期限前に自動で通知し、Excel出力にも対応。<strong>更新漏れは法令違反に直結するため、人の記憶に頼らない設計にしました。</strong>",
         en:"Every residence card with its expiry and the days remaining, warned about well in advance and exportable to Excel. <strong>A missed renewal is a legal problem, so nothing here depends on somebody remembering.</strong>"},
"d.k6h":{ja:"採用管理",en:"Recruitment"},
"d.k6p":{ja:"応募者を9つのタブ（経歴・学歴・スキル・デモ授業・適性など）で管理。最寄駅から通勤可能な学校を自動判定し、スコアを付けて選考します。",
         en:"Applicants held across nine tabs — career, education, skills, demo lesson, matching and more — with the nearest station used to work out which schools they can realistically reach, and a score attached to each."},
"d.k7h":{ja:"評価・月次報告",en:"Reviews & reporting"},
"d.k7p":{ja:"月次報告を構造化フォームで収集し、AIで傾向を分析。学校訪問時の評価記録もここに集約されます。",
         en:"Monthly reports collected through a structured form and summarised with AI, together with the assessment notes from my own school visits."},
"d.k8h":{ja:"社内連絡・お知らせ",en:"Internal comms"},
"d.k8p":{ja:"市町村ごとに配信先を絞れる社内ニュース、匿名アンケート、市別のグループチャット、共有ファイルのピン留め機能を備えています。",
         en:"Internal news targeted city by city, anonymous staff polls, group chat organised by city, and shared files pinned where everyone can find them."},
"d.k9h":{ja:"分析とレポート",en:"Analytics"},
"d.k9p":{ja:"年度・市町村・個人で絞り込み、遅刻率や欠勤率を自動算出。推移グラフと市町村比較を表示し、PDF・CSV・Excelで出力できます。",
         en:"Filter by school year, city or individual; late and absence rates calculated for you; trend lines and city comparisons on screen; export to PDF, CSV or Excel."},
"d.note":{ja:"さらに、労働者派遣法のガイド（3年ルール、同一労働同一賃金、禁止事項）と、質問に日本語で答えるAIアシスタントを内蔵しています。ハラスメントや職場環境に関する相談窓口も、緊急度付きのチケットとして管理しています。",
          en:"It also carries a guide to Japanese dispatch law — the three-year rule, equal pay for equal work, prohibited activities — with an AI assistant that answers questions about it, and a support-ticket queue for harassment, safety and payroll concerns, graded by urgency."},

/* ── OPS APPS ── */
"o.eye":{ja:"社員向けアプリ",en:"Apps for staff"},
"o.h":{ja:"事務作業を、<em>アプリに置き換える</em>",en:"Paperwork,<em> turned into software</em>"},
"o.lead":{ja:"外国籍社員が大半を占める会社では、日本語の書類そのものが障壁になります。年末調整、在留資格の更新、確定申告、健康保険——どれも本人には読めません。だから読めるものに作り替えました。",
          en:"When most of your staff are not Japanese, the paperwork itself is the obstacle. Year-end tax adjustment, visa renewal, tax filing, health insurance — none of it is readable to the person who has to complete it. So I rebuilt it into something they can read."},

"o.g1n":{ja:"Brain Power ガイド",en:"Brain Power Guide"},
"o.g1s":{ja:"日本で働き、暮らすための実務ガイド（一般公開中）",en:"Working and living in Japan — publicly live"},
"o.g1p":{ja:"在留資格、税金、ハローワーク、家計、緊急時対応、用語集を平易な英語で解説したガイドサイト。さらに実際に動く2つのツールを内蔵しています。<strong>高度専門職ポイント計算機</strong>は、学歴・職歴・年収・加点項目から永住許可の優遇要件（70点／80点）を試算します。<strong>レッスンプラン・アーキテクト</strong>は、3P構成・T1/T2の役割分担・時間配分・SMART目標チェックリストを備えた指導案作成ツールで、そのまま印刷できます。",
         en:"A reference site covering residence status, taxes, Hello Work, budgeting, emergencies and terminology in plain English — with two working tools inside it. The <strong>Highly Skilled Professional points calculator</strong> works out where someone stands against the 70- and 80-point thresholds for accelerated permanent residency from their education, career, salary and bonus points. The <strong>Lesson Plan Architect</strong> builds a lesson around the three Ps, splits every stage between T1 and T2, totals the timing and runs a SMART-goal checklist, then prints."},
"o.g1c1":{ja:"一般公開",en:"Publicly live"},
"o.g1c2":{ja:"永住ポイント計算機",en:"PR points calculator"},
"o.g1c3":{ja:"指導案作成ツール",en:"Lesson plan builder"},
"o.g1c4":{ja:"全10セクション",en:"10 sections"},
"o.g1b":{ja:"実際に触ってみる",en:"Try it live"},

"o.g2n":{ja:"年末調整ヘルパー",en:"Year-End Tax Helper"},
"o.g2s":{ja:"読めない書類を、答えられる質問に",en:"An unreadable form, turned into answerable questions"},
"o.g2p":{ja:"年末調整の書類は、日本人でも難解です。これを6ステップの質問形式に分解し、各項目に説明を添えました。本人情報・所得・配偶者・扶養家族・各種控除を順に答えるだけで、提出できる書類が生成されます。英語のラベルに日本語の記入例を併記しているため、そのまま会社に提出できます。",
         en:"The year-end tax adjustment paperwork defeats Japanese staff, never mind foreign ones. I broke it into six steps of ordinary questions with an explanation attached to every field — personal details, income, spouse, dependants, deductions — and it generates the completed forms at the end. Labels are in English with Japanese example values beside them, so what comes out is what the company needs."},
"o.g2c1":{ja:"6ステップ入力",en:"Six guided steps"},
"o.g2c2":{ja:"書類自動生成",en:"Generates the forms"},
"o.g2c3":{ja:"日英併記",en:"Bilingual labels"},

"o.g3n":{ja:"BP ウェルネスハブ",en:"BP Wellness Hub"},
"o.g3s":{ja:"健康経営のための社内プラットフォーム",en:"A staff health platform"},
"o.g3p":{ja:"目標達成率をリング表示するデイリーゴール、歩数集計、社員が投稿できるレシピ共有、フィットネスのヒント、社内チャレンジ。健康診断の受診率や運動習慣を、義務ではなく参加型の仕組みで底上げすることを狙った設計です。",
         en:"Daily goals shown as a completion ring, step totals, a recipe board staff post to themselves, fitness tips and company challenges. The point was to lift participation in health habits by making it something people join in with rather than something they are told to do."},
"o.g3c1":{ja:"デイリーゴール",en:"Daily goals"},
"o.g3c2":{ja:"社員投稿型レシピ",en:"Staff-posted recipes"},
"o.g3c3":{ja:"社内チャレンジ",en:"Company challenges"},

"o.g4n":{ja:"BP アチーブメント",en:"BP Achievements"},
"o.g4s":{ja:"評価されにくい仕事を、見えるようにする",en:"Making invisible good work visible"},
"o.g4p":{ja:"教頭先生への挨拶、職員会議への参加、清掃活動の手伝い、学校だよりの英訳、テスト採点の補助——学校で評価される行動は、本社からは見えません。これを54個の実績として定義し、本人が証拠を添えて申請、承認されるとメダルとランクが上がる仕組みにしました。研修で伝えるより、行動が変わります。",
         en:"Greeting the vice-principal, sitting in on a staff meeting, helping with the school clean, translating the school newsletter, marking test papers — the behaviour that earns a teacher respect at their school is invisible from head office. I defined 54 of them as achievements, staff submit evidence, and approved ones award a medal and move them up a rank. It changes behaviour in a way a training session does not."},
"o.g4c1":{ja:"54種の実績",en:"54 achievements"},
"o.g4c2":{ja:"証拠提出・承認フロー",en:"Evidence & approval"},
"o.g4c3":{ja:"ランク制度",en:"Rank progression"},

"o.moreh":{ja:"同じプラットフォーム上の、その他の業務システム",en:"Also on the platform"},
"o.morep":{ja:"いずれも紙とExcelで行っていた業務を置き換えたものです。",en:"Each of these replaced something that used to be paper and spreadsheets."},
"o.m1h":{ja:"デジタル出退勤",en:"Digital check-in"},
"o.m1p":{ja:"出勤打刻と、遅刻・欠勤の自動通知。担当者は朝の時点で全員の状況を把握できます。",
         en:"Clocking in, with automatic late and absence notifications, so the office knows where everyone is by the start of the morning."},
"o.m2h":{ja:"デジタル勤務表",en:"Digital timesheet"},
"o.m2p":{ja:"提出・回収・集計を自動化。未提出者への催促も自動で送ります。",
         en:"Submission, collection and totalling automated, and the chasing of late submissions automated too."},
"o.m3h":{ja:"月次レビューシート",en:"Monthly review sheet"},
"o.m3p":{ja:"構造化フォームで回収し、自動で集計。AIで全体の傾向を要約します。",
         en:"Collected through a structured form, totalled automatically, and summarised with AI to show the pattern across everyone."},
"o.m4h":{ja:"有給・休暇申請フォーム",en:"Time-off request form"},
"o.m4p":{ja:"申請から承認、代替教員の手配、振替日設定までを一本の流れに。",
         en:"Request, approval, substitute arrangement and make-up scheduling as one continuous flow."},
"o.m5h":{ja:"在留資格アップデーター",en:"Visa info updater"},
"o.m5p":{ja:"在留期限を管理し、更新期日の前に自動でリマインドします。",
         en:"Tracks every residence status and reminds people ahead of the renewal deadline."},
"o.m6h":{ja:"一斉メール配信",en:"Bulk email sender"},
"o.m6p":{ja:"対象者を絞り込んで社内通知を一斉配信。到達状況も記録されます。",
         en:"Filtered internal announcements sent to the right group at once, with delivery recorded."},

"o.g5n":{ja:"ALTガイド（社員ハンドブック）",en:"ALT Guide — the employee handbook"},
"o.g5s":{ja:"社内規定と研修資料を、検索できる一冊に（一般公開中）",en:"Company rules and training, in one searchable book — publicly live"},
"o.g5p":{ja:"紙で配っていた就業規則と研修資料を、全11章＋付録のWebハンドブックに作り直しました。着任準備、日本での生活、ALTの役割、プロフェッショナリズム、授業の進め方、日本の文化と教育制度、学校での一日、よくある課題、サポート窓口、そして<strong>社内規定・教室で使う日本語フレーズ・用語集</strong>の付録まで。全文検索とダークモードを備え、新任研修はこれを教材として進めます。",
         en:"The employment rules and training material that used to be handed out on paper, rebuilt as an eleven-chapter web handbook with appendices: preparing to start, daily life in Japan, the ALT's role, professionalism, how to teach, Japanese culture and the education system, a day at school, common challenges, where to get help, and appendices for <strong>company policies, classroom Japanese phrases and a glossary</strong>. Full-text search and a dark mode. Induction training runs off it."},
"o.g5c1":{ja:"一般公開",en:"Publicly live"},
"o.g5c2":{ja:"全11章＋付録3",en:"11 chapters + 3 appendices"},
"o.g5c3":{ja:"全文検索",en:"Full-text search"},
"o.g5c4":{ja:"研修教材として使用",en:"Used for induction"},
"o.g4b":{ja:"アプリを開く（Googleログインが必要）",en:"Open the app (Google sign-in required)"},
"z.l8b":{ja:"ALTガイド",en:"ALT Guide"},
"z.l8":{ja:"社員ハンドブック — 一般公開中",en:"The employee handbook — publicly live"},
"z.l9b":{ja:"ウェルネスハブ",en:"Wellness Hub"},
"z.l9":{ja:"健康促進プラットフォーム — 一般公開中",en:"The staff health platform — publicly live"},

/* ── TEACHER APPS ── */
"t.eye":{ja:"教員向けアプリ — bplabo.jp",en:"Apps for teachers — bplabo.jp"},
"t.h":{ja:"教員が毎日使っている、<br><em>10本のアプリ</em>",en:"Ten apps<br><em>the teachers use every day</em>"},
"t.lead":{ja:"BP Labo の中身です。ALTは日本人の英語教師とチームで授業を行います。準備時間は限られ、教室のPC環境もまちまちです。そこで、<strong>ブラウザだけで動き、日本の学習指導要領の学年区分（小1〜6・中1〜3）に沿った</strong>アプリを作りました。教室で児童・生徒の前に出して使うものと、<strong>BP-Planner・BP-Cap'N'Play・BP-Roles のように、児童は一度も目にしない授業準備・打合せ用のもの</strong>があります。すべて実際に使われ、教員のフィードバックを受けて改良を重ねています。",
          en:"These live inside BP Labo. An ALT teaches alongside a Japanese teacher of English. Preparation time is short and the equipment in each classroom is different, so I built apps that <strong>run in nothing but a browser and follow the Japanese grade structure</strong> — elementary years 1 to 6, junior high 1 to 3. Some are put up on the projector in front of a class. Others — <strong>BP-Planner, BP-Cap'N'Play and BP-Roles</strong> — no student ever sees: they are lesson-planning and teacher-to-teacher tools. All of them are in real use, and all of them have been rebuilt on the back of what teachers said."},

"t.a1n":{ja:"BP-Tools",en:"BP-Tools"},
"t.a1s":{ja:"教室用ツール8種を1画面に",en:"Eight classroom tools on one screen"},
"t.a1p":{ja:"日付と天気、授業タイマー、ランダム指名、絵カード、チーム得点板、そして3種類の語彙ゲーム（What's Missing／画像リビール／ビンゴ）。各パネルは全画面表示に切り替えられ、プロジェクタでそのまま使えます。語彙はカテゴリ単位で共有され、どのゲームからも同じカードを呼び出せます。",
         en:"Date and weather, a lesson timer, a random student picker, picture flashcards, a team scoreboard, and three vocabulary games — What's Missing, Image Reveal and Bingo. Every panel expands to full screen for the projector, and all the games draw from the same shared picture-word categories."},
"t.a1c1":{ja:"8種のツール",en:"Eight tools"},
"t.a1c2":{ja:"全画面表示",en:"Full-screen mode"},
"t.a1c3":{ja:"共有カテゴリ",en:"Shared word sets"},
"t.a1c4":{ja:"クラス名簿の保存",en:"Saved class lists"},

"t.a2n":{ja:"BP-Expo",en:"BP-Expo"},
"t.a2s":{ja:"世界25か国を旅する国際理解教育ツール",en:"A world atlas for global education"},
"t.a2p":{ja:"イラストの世界地図から国を選ぶと、基本情報・文化・学校生活・クイズの4セクションが開きます。内容は意図的に<strong>日本の児童が自分と比べられる話題</strong>——登校時間、給食、休み時間の遊び、部活動——に寄せています。音声読み上げと日英切替を全ページに備えました。",
         en:"Students pick a country off an illustrated world map and get four sections — general information, culture, school life and a quiz. The content is deliberately framed around <strong>things a Japanese child can compare to their own life</strong>: what time school starts, what they eat for lunch, what they play at break, what clubs they join. Audio narration and an EN/JP switch on every page."},
"t.a2c1":{ja:"25か国収録",en:"25 countries"},
"t.a2c2":{ja:"日英切替",en:"EN/JP toggle"},
"t.a2c3":{ja:"音声読み上げ",en:"Audio narration"},

"t.a3n":{ja:"BP-Talk",en:"BP-Talk"},
"t.a3s":{ja:"AIキャラクターと英会話を練習する",en:"Speaking practice with an AI character"},
"t.a3p":{ja:"生徒がマイクに向かって話すと、画面上のキャラクターが応答します。自由会話（自己紹介・好き嫌い・趣味）と、小5・小6の教科書に沿った会話練習コースの2モード。詰まったときのために<strong>ヒント</strong>と<strong>スキップ</strong>を用意しました。相手が人間ではないので、間違いを恐れずに何度でも話せます。",
         en:"A student taps the microphone and talks; the character on screen answers. Two modes — open Free Chat on introductions, likes and hobbies, and a graded practice course following the Grade 5 and Grade 6 textbooks. <strong>Hint</strong> and <strong>Skip</strong> are always there for a student who freezes. Because it is not a person, they will try again as many times as they need to."},
"t.a3c1":{ja:"AI会話",en:"AI conversation"},
"t.a3c2":{ja:"音声認識",en:"Speech recognition"},
"t.a3c3":{ja:"学年別コース",en:"Graded courses"},

"t.a4n":{ja:"BP-Shout",en:"BP-Shout"},
"t.a4s":{ja:"発音練習を、ゲームにする",en:"Pronunciation drill as a game"},
"t.a4p":{ja:"単語カードが画面手前に迫ってくる間に、生徒が声に出して発音します。アプリが音声を認識して採点し、1ラウンド10問。正解で貯まるポイントで、アバターの髪型・眼鏡・帽子・服を解放できます。<strong>発音練習という一番嫌がられる作業に、続ける理由を付けました。</strong>",
         en:"A word card rushes toward the player and the student has to say it out loud. The app listens, scores it, and moves through a round of ten. Points earned unlock hair, glasses, hats and clothes for their character. <strong>It gives the least popular drill in language teaching a reason to keep going.</strong>"},
"t.a4c1":{ja:"音声認識採点",en:"Scored by speech recognition"},
"t.a4c2":{ja:"アバター育成",en:"Character unlocks"},
"t.a4c3":{ja:"10問1ラウンド",en:"Ten-word rounds"},

"t.a5n":{ja:"BP-Planner",en:"BP-Planner"},
"t.a5s":{ja:"AIが指導案を書き、担任との打合せまで支える",en:"AI lesson plans, and the meeting that follows"},
"t.a5p":{ja:"学年・教科書・単元を選ぶと、45分の指導案が生成されます。重要なのは<strong>全工程がALT側とJTE側の2列に分かれている</strong>ことです。日本の教室はT1/T2の役割分担で動くため、ここが曖昧だと授業が崩れます。SMART目標、語彙、教材リスト、時間配分付き。日本の教室で定番の活動（かるた、しりとり、フルーツバスケット等）のデータベースも内蔵し、授業後は5段階評価と生徒の反応記録を残せます。",
         en:"Pick a grade, a textbook and a unit and it writes a 45-minute plan. What matters is that <strong>every stage is split into an ALT column and a JTE column</strong> — a Japanese classroom runs on a T1/T2 division of labour, and a plan that leaves it vague falls apart in the room. SMART goal, vocabulary, materials and timings included. A database of the classic Japanese-classroom activities (karuta, shiritori, fruit basket) sits alongside it, and after the lesson the teacher files a star rating and a record of how the class responded."},
"t.a5c1":{ja:"AI指導案生成",en:"AI plan generation"},
"t.a5c2":{ja:"T1/T2役割分担",en:"T1 / T2 roles"},
"t.a5c3":{ja:"活動データベース",en:"Activity database"},
"t.a5c4":{ja:"授業後の振り返り",en:"Post-lesson reflection"},

"t.a6n":{ja:"BP-Tango",en:"BP-Tango"},
"t.a6s":{ja:"学年別・35カテゴリの絵カード集",en:"Picture cards, 35 categories, by grade"},
"t.a6p":{ja:"学年（小1〜中3）とカテゴリを選ぶと、その学年で扱う語彙のカードセットが出来上がります。1枚ずつの表示と、教室の壁のように一覧表示する2モード。裏面には<strong>カタカナ・ひらがな・漢字の3表記</strong>を載せているため、日本人教師もそのまま使えます。教員が独自のセットを作って保存・共有することもできます。",
         en:"Choose a grade — elementary 1 through junior high 3 — and the categories you want, and you get the card set for that year's vocabulary. Show them one at a time, or as a whole wall of cards. The reverse of each card carries <strong>katakana, hiragana and kanji</strong>, so the Japanese teacher can use it as readily as the ALT. Teachers build and save their own sets too."},
"t.a6c1":{ja:"35カテゴリ",en:"35 categories"},
"t.a6c2":{ja:"小1〜中3対応",en:"Grades 1–9"},
"t.a6c3":{ja:"日本語3表記",en:"Three Japanese scripts"},

"t.a7n":{ja:"BP-Cap'N'Play",en:"BP-Cap'N'Play"},
"t.a7s":{ja:"学年とテーマから、授業ゲームを生成する",en:"Generates classroom games from a topic"},
"t.a7p":{ja:"「中1・学校生活」と指定すると、ウォームアップ1本とメインゲーム2本が生成されます。各ゲームには所要時間、必要教材、準備手順、進め方、まとめ、そして<strong>ALT用とJTE用それぞれの一人称の台本</strong>が付きます。そのまま印刷して教室に持ち込めます。生成した授業はセッションとして保存され、生徒の反応も記録されます。",
         en:"Ask for \"junior high 1, school life\" and it produces a warm-up and two main games. Each one comes with a duration, a materials list, numbered setup and play instructions, a wrap-up, and <strong>a first-person script for the ALT and another for the Japanese teacher</strong>. Print it and walk into the room. Generated lessons are saved as sessions with a record of how the class reacted."},
"t.a7c1":{ja:"AIゲーム生成",en:"AI game generation"},
"t.a7c2":{ja:"教員別台本",en:"Per-teacher scripts"},
"t.a7c3":{ja:"印刷対応",en:"Print-ready"},

"t.a8n":{ja:"BP-Pay",en:"BP-Pay"},
"t.a8s":{ja:"QRコードで買い物する、お金の授業",en:"A shopping role-play that runs on QR codes"},
"t.a8p":{ja:"生徒一人ひとりにデジタルの財布を配り、教室に貼った商品カードのQRコードを読み取って「買い物」をします。残高がリアルタイムで減るため、価格と数量の英語表現が実感を伴います。教員側は残高の追加、クーポン発行、直前の購入の取り消し、ラウンドのリセットができます。",
         en:"Every student gets a digital wallet and buys things by scanning the QR codes on product cards around the room. The balance falls as they spend, so the language of prices and quantities lands with something real behind it. The teacher can top wallets up, issue coupons, undo the last purchase and reset the round."},
"t.a8c1":{ja:"QRコード決済",en:"QR-code shopping"},
"t.a8c2":{ja:"残高リアルタイム表示",en:"Live balances"},
"t.a8c3":{ja:"教員コントロール",en:"Teacher controls"},

"t.a9n":{ja:"BP-Roles",en:"BP-Roles"},
"t.a9s":{ja:"QRコードで担任と指導案を共有する",en:"Pairing with the Japanese teacher by QR code"},
"t.a9p":{ja:"指導案を学校・学年・クラス・実施日で整理し、絞り込めるようにしたアプリです。特徴は<strong>QRコードによる教員同士のアカウント連携</strong>で、ALTと日本人教師が互いのコードを読み取るだけで指導案を共有できます。打合せの前に、同じ資料を両者が見られる状態を作るための仕組みです。",
         en:"Lesson plans filed by school, grade, class and date, and filterable on any of them. Its distinguishing feature is <strong>QR-code pairing between teachers</strong> — the ALT and the Japanese teacher scan each other's code and their plans are shared. The point is that both people are looking at the same document before the planning meeting starts."},
"t.a9c1":{ja:"QR連携",en:"QR pairing"},
"t.a9c2":{ja:"学校別・学年別管理",en:"Filed by school & grade"},

/* ── TALENTDESK ── */
"td.eye":{ja:"02 — talentdesk.jp",en:"02 — talentdesk.jp"},
"td.h":{ja:"派遣プログラム全体を、<br><em>ひとつのMSPで運営する。</em>",en:"A whole staffing programme,<br><em>run as one managed service.</em>"},
"td.lead":{ja:"Brain Power が<strong>MSP（マネージド・サービス・プロバイダ）</strong>として派遣プログラム全体を引き受けるためのプラットフォームです。クライアント企業である株式会社フジキンが人材を要求し、Brain Power が登録済みの協力会社——<strong>社数に制限はありません</strong>——へ配信し、集まった候補者を選考してクライアントに提示します。案件の作成から就業開始まで一本の流れでつながり、労働者派遣法が定める2つの抵触日を実際の日付から計算して数か月前に警告します。26画面・日英完全対応。",
          en:"The platform Brain Power runs as a <strong>managed service provider</strong> for an entire staffing programme. Fujikin, the client, raises a request; Brain Power releases it to the registered supplier agencies — <strong>however many there are</strong> — screens whoever comes back, and puts the shortlist in front of the client. Every step from request to first day on site is one continuous chain, and both three-year limits Japanese dispatch law imposes are calculated from real dates and warned about months ahead. 26 screens, fully bilingual."},
"td.k1h":{ja:"3種類のポータル",en:"Three kinds of portal"},
"td.k1p":{ja:"MSPを運営するBrain Power、クライアント企業、そして協力会社。何社増えても入口は同じで、見える範囲はデータベース側で制御します。",
          en:"One for Brain Power running the programme, one for the client, one for each supplier agency however many join — with visibility enforced in the database, not by hiding buttons."},
"td.k2h":{ja:"抵触日の自動監視",en:"The legal clocks, watched"},
"td.k2p":{ja:"事業所単位・個人単位の2つの期限を自動計算し、事前警告と協力会社への通知記録まで残します。",
          en:"Both limits calculated automatically, warned about in advance, with the notice sent to each agency kept on record."},
"td.k3h":{ja:"AIによる選考支援",en:"AI screening support"},
"td.k3p":{ja:"候補者を案件内容に対して採点し要約を生成。判断そのものは人が行う設計です。",
          en:"Candidates scored against the job post and summarised, with the decision itself deliberately left to a person."},
"td.b1":{ja:"製品紹介プレゼンを見る（全26ページ）",en:"Open the full product walkthrough (26 pages)"},
"td.b2":{ja:"talentdesk.jp",en:"talentdesk.jp"},
"td.invite":{ja:"<b>TalentDesk の中を実際にご覧になりたい場合は、管理者ユーザーとしてご招待いたします。</b> ご希望の方は <a href=\"mailto:don@brain-power.jp\">don@brain-power.jp</a> まで、招待をお送りするメールアドレスをお知らせください。",
             en:"<b>If you would like to look round TalentDesk itself, I can invite you in as an admin user.</b> Email <a href=\"mailto:don@brain-power.jp\">don@brain-power.jp</a> with the address you would like the invitation sent to."},
"td.note":{ja:"※ 詳細は別途作成した製品紹介プレゼンテーションをご覧ください。画面ごとの解説を日英両方で収録しています。",
           en:"A separate product walkthrough covers this system screen by screen, in both languages."},

/* ── CORPORATE WEBSITE ── */
"w.eye":{ja:"コーポレートサイト リニューアル",en:"Corporate website redesign"},
"w.h":{ja:"イラストも、実装も、<br><em>すべて自分の手で。</em>",
       en:"Every illustration,<br><em>and the site they live in.</em>"},
"w.lead":{ja:"Brain Power のコーポレートサイトを全面的に作り直しました。<strong>掲載しているイラストは66点すべて自分で描いたもの</strong>です。大阪の街並み、通天閣、たこ焼きの屋台、学校、そこを歩く人々。素材集を使えば早いのですが、それでは「どこかで見たサイト」にしかなりません。スクロールに連動して情景が動き、風景の中を進んでいくように読み進められる構成にしています。",
         en:"A complete rebuild of the Brain Power corporate site. <strong>All 66 illustrations on it are my own drawings</strong> — the Osaka streetscape, Tsūtenkaku, the takoyaki stand, the schools, and the people moving through them. Stock artwork would have been faster and the result would have looked like everybody else's site. The scenes move as you scroll, so reading the page feels like travelling through the landscape."},
"w.btn":{ja:"サイトを開いて実際に触ってみる",en:"Open the site and try it"},
"w.k1h":{ja:"66点のオリジナルイラスト",en:"66 original illustrations"},
"w.k1p":{ja:"背景、建物、人物、小物まですべて描き起こし。既製の素材は使っていません。",
         en:"Backgrounds, buildings, characters and props, all drawn from scratch. No stock assets."},
"w.k2h":{ja:"スクロール連動アニメーション",en:"Scroll-driven animation"},
"w.k2p":{ja:"GSAP ScrollTrigger と Lenis による滑らかなスクロールと、奥行きのある視差表現。",
         en:"GSAP ScrollTrigger and Lenis for smooth scrolling and layered parallax depth."},
"w.k3h":{ja:"対象者別の導線",en:"Three audiences, three routes"},
"w.k3p":{ja:"求職者・学校・海外からの応募者で入口を分け、それぞれに必要な情報だけを届けます。",
         en:"Job seekers, schools and overseas applicants each get their own entrance and only the information that concerns them."},
"w.note":{ja:"※ スクロールで情景が変化するサイトのため、静止画では動きが伝わりません。上のスクリーンショットは各ページの代表的な場面です。",
          en:"The page is built around movement, which a still cannot show. The captures above are representative moments from each page."},

/* ── AI ── */
"a.eye":{ja:"AI・業務自動化",en:"AI & automation"},
"a.h":{ja:"AIに<em>判断させない</em>。<br>AIに<em>準備させる</em>。",en:"I don't let AI <em>decide</em>.<br>I let it <em>prepare</em>."},
"a.lead":{ja:"私が作るAI機能には共通の原則があります。<strong>最終判断は必ず人が行う</strong>ということです。AIは候補を並べ、要約し、下書きを作り、優先順位を付ける。決めるのは人間です。この線引きがあるから、業務に組み込んでも壊れません。以下はすべて、実際に社内で稼働している仕組みです。",
          en:"Everything I build with AI follows one rule: <strong>a person makes the final call.</strong> The AI shortlists, summarises, drafts and ranks; the human decides. That line is why these hold up in daily use rather than becoming something staff route around. Everything below is running in production."},
"a.hireh":{ja:"採用フローの再設計",en:"The hiring pipeline, rebuilt"},
"a.h1b":{ja:"応募",en:"Application"},
"a.h1s":{ja:"オンライン応募フォームを自動送信。",en:"An online form goes out automatically."},
"a.h2b":{ja:"情報収集",en:"Details in"},
"a.h2s":{ja:"経歴・在留資格・最寄駅を構造化して取得。",en:"Career, visa status and nearest station captured as structured data."},
"a.h3b":{ja:"デモ授業",en:"Demo lesson"},
"a.h3s":{ja:"応募者が模擬授業の動画をアップロード。",en:"The applicant uploads a video of themselves teaching."},
"a.h4b":{ja:"AI採点",en:"AI scoring"},
"a.h4s":{ja:"AIが動画を評価し、スコアと要約を生成。",en:"AI grades the video and writes a score and a summary."},
"a.h5b":{ja:"通勤判定",en:"Reachability"},
"a.h5s":{ja:"最寄駅から通勤可能な学校を自動で判定。",en:"Which schools that person can actually reach, worked out from their station."},
"a.h6b":{ja:"選考",en:"Decision"},
"a.h6s":{ja:"担当者が並べて比較し、採否を判断。",en:"A person compares them side by side and decides."},
"a.hirenote":{ja:"以前は履歴書がバラバラの書式でメール添付され、比較するには一通ずつ開くしかありませんでした。現在は同じ形式で並び、デモ授業の評価まで揃った状態で判断できます。私はこのフローの設計・構築と、応募者情報の収集・管理・運用を担当しています。",
              en:"Applications used to arrive as attachments in whatever format the applicant chose, and comparing ten people meant opening ten files. Now they line up in the same shape with the demo lesson already assessed. I designed and built this flow, and I run it."},
"a.c1h":{ja:"メールの監視と緊急度判定",en:"Inbox triage by urgency"},
"a.c1p":{ja:"社員から届くメールをAIが読み、緊急度を4段階に分類します。高・緊急に該当するものは即座に通知され、内容に応じた返信の下書きも生成されます。タスクボードに自動で起票されるため、対応漏れが構造的に起きません。",
         en:"AI reads the mail coming in from staff and grades it across four levels of urgency. Anything high or urgent raises a notification straight away and a draft reply is written for it. Each one is filed onto the task board automatically, so nothing can quietly go unanswered."},
"a.c2h":{ja:"派遣法アシスタント",en:"Dispatch law assistant"},
"a.c2p":{ja:"労働者派遣法（3年ルール、同一労働同一賃金、禁止事項、契約・通知義務）について、担当者が日本語でも英語でも質問できるAIアシスタント。厚生労働省のガイドラインに基づき、回答には注意書きを添えています。",
         en:"Staff can ask questions about the Worker Dispatch Act — the three-year rule, equal pay for equal work, prohibited activities, contract and notification duties — in either language. It is grounded in the Ministry of Health, Labour and Welfare guidance and every answer carries a caution."},
"a.c3h":{ja:"授業コンテンツの生成",en:"Classroom content generation"},
"a.c3p":{ja:"BP-Planner と BP-Cap'N'Play では、学年・教科書・単元から指導案とゲームを生成します。生成物は必ず教員が編集できる形で提供し、使用後の評価がシステムに戻る設計にしています。",
         en:"BP-Planner and BP-Cap'N'Play generate plans and games from a grade, a textbook and a unit. What comes out is always editable by the teacher, and their verdict on how it went feeds back into the system."},
"a.c4h":{ja:"書類処理の自動化",en:"Document automation"},
"a.c4p":{ja:"勤務表、有給申請、通勤届、在留資格書類、在職証明書、日報・月報。定型書類の作成と回収を自動化し、期限管理とアラートを組み合わせています。",
         en:"Timesheets, leave requests, commuting forms, visa paperwork, employment certificates, daily and monthly reports — generated and collected automatically, with deadline tracking and alerts wrapped around them."},
"a.harnessh":{ja:"AIエージェント構築",en:"Agentic engineering"},
"a.harnessp":{ja:"個別の機能を作るだけでなく、<strong>AIエージェントそのものを構築する</strong>ことができます。ハーネス（実行環境）、スキル、ワークフローを設計し、複数の処理を連鎖させて業務を自動化する仕組みです。上記のシステム群は、その考え方の実装例でもあります。",
             en:"Beyond individual features, I <strong>build the agents themselves</strong> — harnesses, skills and workflows that chain steps together and carry a piece of work end to end. The systems above are that way of working, applied."},

/* ── VIDEO ── */
"v.eye":{ja:"映像・アニメーション",en:"Video & animation"},
"v.h":{ja:"教科書に足りないものを、<br><em>自分で作る。</em>",en:"What the textbook lacks,<br><em>I make.</em>"},
"v.lead":{ja:"市販の英語教材には、日本の子どもが実際に習う単元に合った動画がほとんどありません。そこで、企画・脚本・アニメーション・録音・編集・字幕まで一人で制作し、YouTubeチャンネルを立ち上げました。天気、前置詞、所有格、体調表現、季節行事、そして海外在住者へのインタビューによるリスニング教材。全編が教室でそのまま使える長さと内容です。",
          en:"Almost nothing on the market lines up with the units Japanese children are actually taught. So I started a channel and make the videos myself — concept, script, animation, voice recording, editing and subtitles. Weather, prepositions, possessives, talking about being unwell, seasonal events, and listening material built from interviews with people living abroad. All of it cut to a length a teacher can drop straight into a lesson."},
"v.s1":{ja:"公開した動画",en:"Videos published"},
"v.s2":{ja:"チャンネル登録者",en:"Subscribers"},
"v.s3":{ja:"企画から編集まで自作",en:"Made start to finish by me"},
"v.btn":{ja:"YouTubeチャンネルを開く",en:"Open the YouTube channel"},
"v.note":{ja:"※ サムネイルをクリックすると、このページ上で動画が再生されます。",
          en:"Click any thumbnail to play the video here on the page."},

/* ── PPT ── */
"p.eye":{ja:"教材・プレゼンテーション",en:"Teaching materials"},
"p.h":{ja:"PowerPointで<br><em>ゲームを作る。</em>",en:"Building <em>games</em><br>inside PowerPoint."},
"p.lead":{ja:"日本の教室にあるのはPowerPointだけ、という前提から始めています。アニメーション、トリガー、マクロを使い込み、双六、RPG風のダンジョン探索、レースゲーム、宝探し、当てものクイズなどを作りました。特別な環境も追加ソフトも要らず、どの学校のPCでも動きます。以下は実際の授業で使われているものの録画です。",
          en:"These start from the fact that a Japanese classroom has PowerPoint and nothing else. Pushing animations, triggers and macros as far as they go, I have built board games, an RPG-style dungeon crawl, a kart race, treasure hunts and guessing quizzes — no special setup, no extra software, running on whatever PC the school has. Below are recordings of ones in real use."},
"p.note":{ja:"※ サムネイルをクリックすると再生されます。会社行事やビジネスプレゼン用の資料も同様に制作しています。",
          en:"Click a thumbnail to play. I produce the same kind of material for company events and business presentations."},

/* ── MASCOTS ── */
"m.eye":{ja:"キャラクターデザイン",en:"Character design"},
"m.h":{ja:"会社に<em>顔</em>をつくる",en:"Giving the company <em>a face</em>"},
"m.lead":{ja:"社内アプリ、教材、イベント配布物、SNSに一貫して登場するマスコットキャラクターを設計しました。デザイン、3Dモデリング、アニメーション制作まで担当しています。子ども向けの親しみやすさと、企業ブランドとしての統一感を両立させることが狙いです。",
          en:"A cast of mascots that runs through the internal apps, the teaching materials, the event handouts and the social feeds — designed, modelled and animated by me. The brief was to be warm enough for children while still holding together as a company's brand."},
"m.n1":{ja:"BiiPii",en:"BiiPii"},"m.d1":{ja:"案内役のロボット",en:"The guide robot"},
"m.n2":{ja:"Boo",en:"Boo"},"m.d2":{ja:"のんびり屋のクマ",en:"The easy-going bear"},
"m.n3":{ja:"Dr Know",en:"Dr Know"},"m.d3":{ja:"解説役の博士",en:"The professor"},
"m.n4":{ja:"Hammy",en:"Hammy"},"m.d4":{ja:"元気なハムスター",en:"The excitable one"},
"m.n5":{ja:"Snicky",en:"Snicky"},"m.d5":{ja:"好奇心旺盛なリス",en:"The curious squirrel"},
"m.n6":{ja:"Sugar",en:"Sugar"},"m.d6":{ja:"やさしいリス",en:"The gentle one"},
"m.n7":{ja:"Tip",en:"Tip"},"m.d7":{ja:"落ち着いたカエル",en:"The calm frog"},
"m.vt1":{ja:"キャラクター勢揃いアニメーション",en:"The full cast, animated"},
"m.vs1":{ja:"7体すべてを3Dでモデリングし、アニメーションまで制作",en:"All seven modelled in 3D and animated"},

/* ── DESIGN ── */
"g.eye":{ja:"デザイン・広告",en:"Design & advertising"},
"g.h":{ja:"人を集め、<br><em>会社を見せる。</em>",en:"Bringing people in,<br><em>and showing who we are.</em>"},
"g.lead":{ja:"求人広告、SNS投稿、印刷用チラシ、周年ポスター、名刺、ロゴ。Brain PowerとTalentDesk両方のビジュアルアイデンティティを担当し、SNS運用（Instagram・Facebook）も行っています。求人広告は市町村・雇用形態ごとにテンプレート化し、短時間で展開できる形に整理しました。",
          en:"Recruitment ads, social posts, printed flyers, anniversary posters, business cards, logos. I own the visual identity for both Brain Power and TalentDesk, and I run the social accounts. The recruitment ads are templated by city and contract type so a new one can go out quickly."},
"g.logoh":{ja:"ブレーンパワー ロゴ・モーション",en:"Brain Power logo animation"},
"g.logop":{ja:"新ロゴのデザインとアニメーション制作",en:"New logo — designed and animated"},
"g.vt1":{ja:"SNS広告アニメーション",en:"Social advertising animation"},
"g.vs1":{ja:"モーショングラフィックス",en:"Motion graphics"},
"g.vt2":{ja:"吹田・高槻 2学期 募集動画",en:"Suita & Takatsuki recruitment film"},
"g.vs2":{ja:"2分の募集用映像",en:"Two-minute recruitment video"},
"g.p1":{ja:"イングリッシュ・デイ ポスター（味舌小学校 2023-24）",en:"English Day poster — Mashita Elementary, 2023-24"},
"g.p2":{ja:"創立39周年記念ポスター",en:"39th anniversary poster"},
"g.p3":{ja:"京都府国際センター掲示用チラシ",en:"Print flyer — Kyoto Prefectural International Center"},
"g.p4":{ja:"名刺デザイン（40周年記念版）",en:"Business card — 40th anniversary edition"},
"g.p5":{ja:"求人広告（大谷学園・非常勤）",en:"Recruitment ad — Ohtani Gakuen, part-time"},
"g.p6":{ja:"創立38周年記念ポスター",en:"38th anniversary poster"},
"g.p7":{ja:"求人広告（豊能町・短期）",en:"Recruitment ad — Toyono, short term"},
"g.p8":{ja:"SNS求人広告（高槻・常勤）",en:"Social recruitment ad — Takatsuki, full-time"},
"g.p9":{ja:"求人広告（寝屋川・私立小学校）",en:"Recruitment ad — Neyagawa private elementary"},
"g.p10":{ja:"SNS求人広告（大阪・非常勤）",en:"Social recruitment ad — Osaka, part-time"},
"g.p11":{ja:"SNS求人広告（ITエンジニア職）",en:"Social recruitment ad — IT engineer role"},
"g.p12":{ja:"Brain Power ロゴ",en:"Brain Power logo"},
"g.p13":{ja:"TalentDesk ロゴ",en:"TalentDesk logo"},

/* ── EVENT ── */
"e.eye":{ja:"イベント企画・制作物",en:"Events & printed material"},
"e.h":{ja:"一日のために、<br><em>世界をひとつ作る。</em>",en:"Building a whole world<br><em>for a single day.</em>"},
"e.lead":{ja:"イングリッシュ・デイは、学校全体を使った一日がかりの英語イベントです。私は企画、ゲーム設計、配布物のデザイン、印刷手配までを担当しました。児童一人ひとりに配るカードは、<strong>A4を中央で二つ折りにした両面印刷</strong>で、表紙・裏表紙・見開きの4面すべてに役割があります。スタンプを集める台紙であり、キャラクターシートであり、隠し絵探しでもあります。",
          en:"English Day is a whole-school event that takes over the building for a day. I planned it, designed the games, designed the handouts and arranged the printing. Every child gets a card — <strong>A4, double-sided, folded down the middle</strong> — and all four faces do a job. It is a stamp card, a character sheet and a seek-and-find puzzle at once."},
"e.open":{ja:"カードを開く",en:"Open the card"},
"e.close":{ja:"カードを閉じる",en:"Close the card"},
"e.flip":{ja:"裏返す",en:"Turn it over"},
"e.zoom":{ja:"原寸で見る",en:"View full size"},
"e.reset":{ja:"向きを戻す",en:"Reset"},
"e.note":{ja:"ドラッグで自由に回転できます ・ 上のボタンで年度を切り替え",
          en:"Drag to turn it round · pick a year above to change the card"},
"e.moreh":{ja:"歴代のイングリッシュ・デイ配布物",en:"Every year's card, in your hands"},
"e.morep":{ja:"毎年テーマを変え、その年だけの世界観で制作しています。年度を選ぶと、そのカードが実物と同じように机の上に現れます。回して、開いて、裏返してご覧ください。",
           en:"A new theme and a self-contained world each year. Pick a year and that card appears on the table as the real thing — turn it round, open it up, look at the back."},
"e.oside":{ja:"表面",en:"outside"},
"e.zside":{ja:"見開き",en:"inside spread"},
"e.c1":{ja:"Seppi Super Spies",en:"Seppi Super Spies"},
"e.c2":{ja:"Super Seppi World",en:"Super Seppi World"},
"e.c3":{ja:"Settsu Heroes",en:"Settsu Heroes"},

/* ── HR ── */
"hr.eye":{ja:"土台となった経験 — 人事・運営",en:"The ground it stands on — HR & operations"},
"hr.h":{ja:"作るものが刺さるのは、<br><em>その仕事を自分がやっていたからです。</em>",
        en:"What I build lands<br><em>because I did the job first.</em>"},
"hr.lead":{ja:"開発が現在の本業ですが、その出発点はこの実務でした。いまも人事・運営の現場に関わり続けているからこそ、何が面倒で、何が抜け落ちるかを自分で把握でき、直すべき場所がすぐに分かります。以下は、その土台となっている業務範囲です。",
           en:"Development is my job now, but this is where it came from — and I am still close enough to it to see what is tedious and what falls through the cracks. That is what tells me where to point the software. Here is the ground it is built on."},
"hr.c1h":{ja:"勤怠・スケジュール管理",en:"Scheduling & attendance"},
"hr.c1a":{ja:"63名のALTの勤務スケジュールを管理し、日々の変更を反映",en:"Running the working schedules of 63 ALTs and keeping daily changes on the record"},
"hr.c1b":{ja:"欠勤・遅刻の対応と、代替教員の手配",en:"Handling absences and lateness, and arranging substitutes"},
"hr.c1c":{ja:"学校側との調整（10市町村・217校）",en:"Coordinating with the schools — 217 of them across 10 cities"},
"hr.c1d":{ja:"<b>自動カレンダーシステムを構築し、この業務自体を仕組み化</b>",en:"<b>Built the automated calendar system that turned this into a process</b>"},
"hr.c2h":{ja:"採用",en:"Recruitment"},
"hr.c2a":{ja:"応募者情報の収集・管理・データベース運用",en:"Collecting, holding and maintaining applicant information"},
"hr.c2b":{ja:"書類選考のワークフロー設計と運用",en:"Designing and running the screening workflow"},
"hr.c2c":{ja:"デモ授業動画の評価と、面接の実施",en:"Assessing demo lesson videos and interviewing"},
"hr.c2d":{ja:"<b>採用・配属フロー全体を再設計し、自動化</b>",en:"<b>Rebuilt and automated the whole hiring and placement pipeline</b>"},
"hr.c3h":{ja:"研修・人材育成",en:"Training & development"},
"hr.c3a":{ja:"新任ALT研修、および定期ワークショップの企画・実施",en:"Running induction training and regular workshops"},
"hr.c3b":{ja:"社内規定・制度変更の周知と、理解度の確認",en:"Communicating rule and policy changes, and checking they landed"},
"hr.c3c":{ja:"マニュアル・研修資料・ガイド動画の制作",en:"Writing the manuals, the training material and the guide videos"},
"hr.c4h":{ja:"人事評価",en:"Performance assessment"},
"hr.c4a":{ja:"学校訪問による授業観察と、教員ごとの評価記録",en:"School visits to observe lessons and record an assessment for each teacher"},
"hr.c4b":{ja:"改善点の指導と、個別のフォローアップ",en:"Giving the feedback and following it up person by person"},
"hr.c4c":{ja:"月次レビューの収集と傾向分析",en:"Collecting monthly reviews and reading the pattern across them"},
"hr.c4d":{ja:"学校・教育委員会からの評価の集約",en:"Gathering what the schools and boards of education say"},
"hr.c5h":{ja:"労務・書類処理",en:"Employment paperwork"},
"hr.c5a":{ja:"在職証明書、推薦状、各種証明書の発行",en:"Employment certificates, reference letters and other documentation"},
"hr.c5b":{ja:"在留資格の更新書類の作成と、行政書士との連携",en:"Preparing visa renewal documents and working with the company's immigration lawyer"},
"hr.c5c":{ja:"勤務表・有給申請・通勤届・日報月報の処理",en:"Timesheets, leave requests, commuting forms, daily and monthly reports"},
"hr.c5d":{ja:"<b>定型書類を自動生成・自動回収する仕組みを構築</b>",en:"<b>Built the systems that now generate and collect all of it</b>"},
"hr.c6h":{ja:"社内サポート・IT",en:"Support & IT"},
"hr.c6a":{ja:"社員からの問い合わせ対応（AIによる緊急度判定を併用）",en:"Answering staff enquiries, with AI triage sorting them by urgency"},
"hr.c6b":{ja:"ハラスメント・職場環境に関する相談窓口の運営",en:"Running the reporting route for harassment and workplace-safety concerns"},
"hr.c6c":{ja:"PCの修理・構築・初期設定・再インストール等の技術サポート",en:"Hands-on PC support — repair, builds, setup and reinstalls"},

/* ── CLOSE ── */
"z.eye":{ja:"まとめ",en:"In short"},
"z.h":{ja:"いま私がしているのは、<br><em>つくる仕事です。</em>",en:"What I do now<br><em>is build.</em>"},
"z.lead":{ja:"現在の私の主たる役割は<strong>エージェンティック／システムエンジニア</strong>です。ブレーンパワーで動いているソフトウェアは、要件の整理から設計、開発、運用、改修まで、すべて私が担当しています。毎日の仕事はこれです。<br><br>出発点は人事・運営のマネージャーでした。その経験があるからこそ、現場で何が詰まっているのかを自分で見つけ、仕様書も外注も翻訳の往復もなしに、そのまま作って届けられます。実際に、手作業だった業務を次々とシステムに置き換え、<strong>処理量は増え、処理は速くなり、記録は確実に残るようになりました。</strong><br><br>今後もこの方向で進みます。<strong>Web・アプリ・業務システムの開発と、AIエージェントの構築が私の軸です。</strong>そしてこの仕事は場所を選びません。",
          en:"My role now is <strong>agentic / systems engineer</strong>. Every piece of software running at Brain Power is mine — I work out what is needed, design it, build it, ship it and maintain it. That is what I do every day.<br><br>I came to it from HR and operations management, and that is why the software lands: I find the bottleneck myself, on the floor, and build the fix without a specification document, a vendor, or a translation round-trip. Replacing manual process with systems has had the same effect every time — <strong>more work gets through, it gets through faster, and there is a reliable record of it afterwards.</strong><br><br>This is the direction I am going in. <strong>Web, app and business-system development, and building AI agents.</strong> And none of it depends on which room I am sitting in."},
"z.s1":{ja:"自社開発アプリ・サイト",en:"Apps & sites built"},
"z.s2":{ja:"授業用PowerPoint教材",en:"PowerPoint teaching games"},
"z.s3":{ja:"制作した動画",en:"Videos produced"},
"z.s4":{ja:"デザインしたキャラクター",en:"Characters designed"},
"z.l1":{ja:"社内プラットフォーム — 上記の閲覧用アカウントでログイン可",en:"The internal platform — sign in with the guest account above"},
"z.l2":{ja:"MSPプラットフォーム（要ログイン）",en:"The MSP platform — login required"},
"z.l3b":{ja:"TalentDesk 製品紹介",en:"TalentDesk walkthrough"},
"z.l3":{ja:"全26ページの製品紹介プレゼンテーション",en:"The full 26-page product presentation"},
"z.l4b":{ja:"Brain Power ガイド",en:"Brain Power Guide"},
"z.l4":{ja:"一般公開中 — 実際に触れます",en:"Publicly live — you can use it right now"},
"z.l5":{ja:"制作した英語教材動画 15本",en:"15 English teaching videos I produced"},
"z.l6":{ja:"運用中の公式アカウント",en:"The company account I run"},
"z.l7":{ja:"運用中の公式アカウント",en:"The company account I run"},
"z.foot":{ja:"Vittorio Zumpano（Don） ・ ポートフォリオ ・ 2026",en:"Vittorio Zumpano (Don) · Portfolio · 2026"},

/* ── FUJIE STUDIO ── */
"fj.eye":{ja:"コンテスト応募作品 ・ フジキン株式会社「フジィ」",en:"Contest entry · Fujikin's mascot “Fujie”"},
"fj.h":{ja:"フジィは、<br><em>実在する魚です。</em>",en:"Fujie is<br><em>a real fish.</em>"},
"fj.lead":{ja:"フジキン株式会社のマスコットキャラクター「フジィ」のコンテストに応募した作品です。企画・デザイン・実装をすべて一人で担当しました。<strong>フジィは架空のキャラクターではなく、1987年から茨城の水槽で生きている一匹のチョウザメです。</strong>その事実だけを出発点に、育成ゲーム、40年をたどるスクロール年表、子ども向けの第二の姿「ちびフジィ」、128種のLINEスタンプ、この魚のために描き起こした和紋18種、そして5ラインのグッズ展開までを、日英2言語のひとつのサイトにまとめています。",
          en:"My entry to the mascot contest for Fujikin — conceived, designed and built end to end by me. <strong>Fujie is not an invented character. He is a sturgeon that has been swimming in a tank in Ibaraki since 1987.</strong> That one fact is what the whole proposal is built on: a raising game, a forty-year scrolling timeline, a second character form for children, a hundred and twenty-eight LINE stickers, eighteen Japanese patterns drawn for this fish, and five lines of merchandise — one bilingual site."},
"fj.s1":{ja:"LINEスタンプ（日英）",en:"LINE stickers, JA &amp; EN"},
"fj.s2":{ja:"オリジナル和紋",en:"Original patterns"},
"fj.s3":{ja:"グッズライン",en:"Product lines"},
"fj.s4":{ja:"ミニゲーム",en:"Mini-games"},
"fj.s5":{ja:"年分の歴史を1本の年表に",en:"Years on a single timeline"},

"fj.goodsh":{ja:"一匹の魚から、五つの棚へ",en:"One fish, five different shelves"},
"fj.goodsp":{ja:"子どもの棚、贈答の棚、旅行の棚、和柄の棚、工芸の棚。想定する客層ごとに絵柄も素材も価格帯も変えています。社名「フジキン」は富士山に由来するため、水とならぶ第二のモチーフとして富士山を全ラインに通しました。",
             en:"The children's shelf, the gift shelf, the travel shelf, the pattern shelf and the craft shelf — each with its own artwork, materials and price. The name Fujikin comes from the mountain, so Mount Fuji now stands beside the water as the second house motif, on every one of them."},
"fj.p1":{ja:"カプセルトイ 全6ポーズ（ちびフジィ）",en:"Capsule toys, six poses — Chibi Fujie"},
"fj.p2":{ja:"ぬいぐるみ 3サイズ（稚魚・幼魚・成魚）",en:"Plush in three sizes — fry, young fish, grown fish"},
"fj.p3":{ja:"マスコットキーホルダー（最安・最も出歩く一品）",en:"Mascot keychain — the cheapest item and the one that travels furthest"},
"fj.p4":{ja:"公式ライン：型押しレザートート",en:"Official line — blind-debossed leather tote"},
"fj.p5":{ja:"Maison Fujie：モノグラムのトランクケース",en:"Maison Fujie — the monogram trunk case"},
"fj.p6":{ja:"和紋グッズ：青海波の扇子",en:"Wamon goods — seigaiha folding fan"},
"fj.p7":{ja:"工芸ライン：浮世絵木版",en:"Craft line — ukiyo-e woodblock print"},
"fj.p8":{ja:"LINEスタンプ 日本語版 01（全64種）",en:"LINE sticker set 01, Japanese — 64 in the pack"},

"fj.caph":{ja:"このサイトに入っているもの",en:"What is in the site"},
"fj.k1h":{ja:"育成ゲーム「フジィを育てよう」",en:"Raising game — “Raise Fujie”"},
"fj.k1p":{ja:"一粒の卵から成魚まで、約90秒。えさ・遊び・睡眠・水流の4つの世話と、4種のミニゲーム。水流は成長段階に合わせて適正値が動くため、放っておくと育ちません。日英対応。",
          en:"One egg to a grown fish in about ninety seconds. Four kinds of care — feed, play, sleep, flow — and four mini-games. The right flow rate moves as he grows, so he will not grow if he is left alone. Japanese and English."},
"fj.k2h":{ja:"スクロール年表「一粒の卵から」",en:"Scrolling timeline — “From a single egg”"},
"fj.k2p":{ja:"1987年のひと言から、世界初のチョウザメ完全養殖、日本初の国産キャビア、そして40年目の2027年まで。スクロールだけで40年をたどれる構成にしました。",
          en:"From one remark in 1987 to the world's first full-cycle sturgeon farming, Japan's first domestic caviar, and on to 2027, the fortieth year. Forty years in a single scroll."},
"fj.k3h":{ja:"ちびフジィ — 第二の姿",en:"Chibi Fujie — a second form"},
"fj.k3p":{ja:"公式イラストには一切手を加えていません。キャラクターマニュアル第7条の指定どおり原画をそのまま使い、その隣に立つ子ども向けの姿として新たに設計しました。ターンアラウンド、表情シートまで作成。",
          en:"The official Fujie is not touched. As Article 7 of the manual requires, the original artwork is used exactly as supplied; Chibi Fujie is proposed as a second form to stand beside it — the sharp real fish for adults, this one for children. Turnaround and expression sheets included."},
"fj.k4h":{ja:"LINEスタンプ 128種",en:"A hundred and twenty-eight stickers"},
"fj.k4p":{ja:"日本語64種・英語64種。1枚ずつ切り抜き、LINEの規定サイズに合わせています。公式アカウント追加の特典として無料配布する想定。英語版はそのままWhatsAppとTelegramにも使えます。",
          en:"Sixty-four in Japanese, sixty-four in English, every one cut out on its own and finished to the LINE spec. Given away free for adding the official account, so Fujie ends up inside people's conversations. The English set carries straight over to WhatsApp and Telegram."},
"fj.k5h":{ja:"フジィ和紋コレクション 18種",en:"The Fujie pattern collection — eighteen"},
"fj.k5p":{ja:"和柄は昔から意味で選ばれてきました。青海波は海、鱗は魚のうろこ、立涌は昇る流れ、麻の葉は成長。この魚のために選び、この魚のために描き直しています。亀甲の結び目にはバルブのハンドル、遡上を示す矢文、キャビアを小紋に。",
          en:"Japanese patterns have always been chosen for what they mean — seigaiha is the sea, uroko is a fish's scales, tatewaku is rising current, asanoha is growing. Eighteen chosen for this fish and drawn for it: valve handwheels at the tortoise-shell nodes, arrows pointing upstream, caviar as a komon."},
"fj.k6h":{ja:"グッズ5ライン",en:"Five lines of goods"},
"fj.k6p":{ja:"ちびフジィの日用品、公式アートワークだけで組んだ贈答品、レザーと帆布の「Maison Fujie」、和紋の持ち歩き小物、そして浮世絵・金屏風・蒔絵などの工芸。棚も客層も価格帯も別に設計しています。",
          en:"Chibi Fujie's toys and daily things, a gift line built only from the official artwork, “Maison Fujie” in leather and canvas, wamon goods you carry, and the craft line — woodblock, gold screens, maki-e, blue-and-white. A different shelf, buyer and price for each."},
"fj.btn":{ja:"サイトを見る",en:"Open the site"},
"fj.note":{ja:"公式イラストはキャラクターマニュアル ver1.0 第7条に従って使用しています（変形・色変更・透過処理・文字の重ね・要素の追加や削除は一切なし）。ちびフジィ、和紋コレクション、Maisonラインは、その隣に並べる新規提案として制作したものです。",
           en:"The official illustration is used in accordance with Article 7 of the character manual ver 1.0 — no reshaping, recolouring, transparency, overlaid text, or added or removed elements. Chibi Fujie, the pattern collection and the Maison line are new work proposed alongside it."},
};


const NAV = {
hero:{ja:"表紙",en:"Cover"},
intro:{ja:"概要",en:"At a glance"},
flagship:{ja:"主要プロジェクト",en:"Flagships"},
labo:{ja:"BP Labo",en:"BP Labo"},
dash:{ja:"自社開発HRIS",en:"Custom HRIS"},
ops:{ja:"社員向けアプリ",en:"Staff apps"},
teach:{ja:"教員向けアプリ",en:"Teacher apps"},
td:{ja:"TalentDesk",en:"TalentDesk"},
web:{ja:"コーポレートサイト",en:"Corporate site"},
ai:{ja:"AI・自動化",en:"AI & automation"},
video:{ja:"映像",en:"Video"},
ppt:{ja:"教材",en:"Teaching materials"},
mascot:{ja:"キャラクター",en:"Characters"},
design:{ja:"デザイン",en:"Design"},
fuji:{ja:"フジィ・スタジオ",en:"Fujie Studio"},
event:{ja:"イベント",en:"Events"},
hr:{ja:"人事・運営",en:"HR & ops"},
close:{ja:"まとめ",en:"In short"},
};

const MARQ = {
ja:["業務システム設計","Webアプリ開発","AIエージェント構築","ワークフロー自動化","音声認識","データ可視化","帳票・書類自動生成","PDF / Excel 出力","権限・ロール設計","通知・アラート設計","多言語対応（日英）","人事システム（HRIS）","労働者派遣法コンプライアンス","採用フロー設計","イラストレーション","ブランドデザイン","ロゴ・名刺・印刷物","3Dキャラクターデザイン","スクロールアニメーション","モーショングラフィックス","動画編集・字幕制作","PowerPoint 高度活用","研修設計・マニュアル制作","SNS運用","PC構築・保守"],
en:["Business system design","Web application development","AI agent engineering","Workflow automation","Speech recognition","Data visualisation","Document generation","PDF / Excel export","Roles & permissions","Notification design","Bilingual JA / EN delivery","HRIS","Dispatch-law compliance","Recruitment pipeline design","Illustration","Brand design","Logos, cards & print","3D character design","Scroll animation","Motion graphics","Video editing & subtitling","Advanced PowerPoint","Training design & manuals","Social media management","PC builds & support"]
};
